[package]
org = "ballerinax"
name = "kafka"
version = "3.9.1"
authors = ["Ballerina"]
keywords = ["kafka", "event streaming", "network", "messaging"]
repository = "https://github.com/ballerina-platform/module-ballerinax-kafka"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "kafka-native"
version = "3.9.1"
path = "../native/build/libs/kafka-native-3.9.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "2.8.0"
path = "./lib/kafka-clients-2.8.0.jar"

[[platform.java11.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka_2.12"
version = "2.8.0"
path = "./lib/kafka_2.12-2.8.0.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.3.0"
path = "./lib/constraint-native-1.3.0.jar"

[build-options]
observabilityIncluded=true
