[package]
org = "ballerinax"
name = "kafka"
version = "3.6.0"
authors = ["Ballerina"]
keywords = ["kafka", "event streaming", "network", "messaging"]
repository = "https://github.com/ballerina-platform/module-ballerinax-kafka"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.3.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "kafka-native"
version = "3.6.0"
path = "../native/build/libs/kafka-native-3.6.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/kafka-clients-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/kafka_2.12-2.8.0.jar"

#[[platform.java11.dependency]]
#path = "./lib/slf4j-api-1.7.30.jar"
#
#[[platform.java11.dependency]]
#path = "./lib/slf4j-simple-1.7.30.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.0.1"
path = "./lib/constraint-native-1.0.1-20221012-153500-b7200cb.jar"

[build-options]
observabilityIncluded=true
