[package]
org = "ballerinax"
name = "kafka"
version = "4.5.0"
authors = ["Ballerina"]
keywords = ["kafka", "event streaming", "network", "messaging"]
repository = "https://github.com/ballerina-platform/module-ballerinax-kafka"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "kafka-native"
version = "4.5.0"
path = "../native/build/libs/kafka-native-4.5.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "3.7.2"
path = "./lib/kafka-clients-3.7.2.jar"

[[platform.java21.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka_2.12"
version = "3.7.2"
path = "./lib/kafka_2.12-3.7.2.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.7.0"
path = "./lib/constraint-native-1.7.0-20250311-133400-acfb095.jar"

[[platform.java21.dependency]]
groupId = "com.google.guava"
artifactId = "guava"
version = "32.0.1-jre"
path = "./lib/guava-32.0.1-jre.jar"

[[platform.java21.dependency]]
groupId = "org.xerial.snappy"
artifactId = "snappy-java"
version = "1.1.10.7"
path = "./lib/snappy-java-1.1.10.7.jar"

[build-options]
observabilityIncluded=true
