[package]
org = "ballerinax"
name = "kafka"
version = "4.3.0"
authors = ["Ballerina"]
keywords = ["kafka", "event streaming", "network", "messaging"]
repository = "https://github.com/ballerina-platform/module-ballerinax-kafka"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0-20241025-103700-5c9e6a27"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "kafka-native"
version = "4.3.0"
path = "../native/build/libs/kafka-native-4.3.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "3.5.1"
path = "./lib/kafka-clients-3.5.1.jar"

[[platform.java21.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka_2.12"
version = "3.5.1"
path = "./lib/kafka_2.12-3.5.1.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.5.1"
path = "./lib/constraint-native-1.5.1-20240930-123400-5ecd396.jar"

[build-options]
observabilityIncluded=true
