[package]
org = "ballerinax"
name = "kafka"
version = "3.4.0"
authors = ["Ballerina"]
keywords = ["kafka", "event streaming", "network", "messaging"]
repository = "https://github.com/ballerina-platform/module-ballerinax-kafka"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.1.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "kafka-native"
version = "3.4.0"
path = "../native/build/libs/kafka-native-3.4.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/kafka-clients-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/kafka_2.12-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/avro-1.9.2.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.0.0"
path = "./lib/constraint-native-1.0.0-20220718-173500-74bf392.jar"

[build-options]
observabilityIncluded=true
