[package]
org = "ballerinax"
name = "kafka"
version = "3.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/kafka-native-3.0.0.jar"

[[platform.java11.dependency]]
path = "./lib/kafka-clients-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/kafka_2.12-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/avro-1.9.2.jar"

[build-options]
observabilityIncluded=true
