[project]
org-name = "ballerinax"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "kafka"
    version = "1.0.0-SNAPSHOT"
    path = "../kafka-native/build/libs/kafka-native-1.0.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["kafka"]

    [[platform.libraries]]
    artifactId = "kafka"
    version = "1.0.0-SNAPSHOT"
    path = "../kafka-native/build/libs/kafka-test-utils-1.0.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["kafka"]
    scope = "test"

    [[platform.libraries]]
    artifactId = "kafka-clients"
    version = "2.3.1"
    path = "./lib/kafka-clients-2.3.1.jar"
    groupId = "org.apache.kafka"

    [[platform.libraries]]
    artifactId = "kafka_2.12"
    version = "2.3.1"
    path = "./lib/kafka_2.12-2.3.1.jar"
    groupId = "org.apache.kafka"

    [[platform.libraries]]
    artifactId = "avro"
    version = "1.9.2"
    path = "./lib/avro-1.9.2.jar"
    groupId = "org.apache.avro"
