[project]
org-name = "ballerinax"
version = "@toml.version@"

[dependencies]
"ballerina/config" = "@stdlib.config.version@"
"ballerina/file" = "@stdlib.file.version@"
"ballerina/filepath" = "@stdlib.filepath.version@"
"ballerina/io" = "@stdlib.io.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/runtime" = "@stdlib.runtime.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/time" = "@stdlib.time.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "kafka"
    version = "@project.version@"
    path = "../kafka-native/build/libs/kafka-native-@project.version@.jar"
    groupId = "org.ballerinalang.messaging.kafka"
    modules = ["kafka"]

    [[platform.libraries]]
    artifactId = "kafka-clients"
    version = "@kafka.version@"
    path = "./lib/kafka-clients-@kafka.version@.jar"
    groupId = "org.apache.kafka"

    [[platform.libraries]]
    artifactId = "kafka_2.12"
    version = "@kafka.version@"
    path = "./lib/kafka_2.12-@kafka.version@.jar"
    groupId = "org.apache.kafka"

    [[platform.libraries]]
    artifactId = "avro"
    version = "1.9.2"
    path = "./lib/avro-1.9.2.jar"
    groupId = "org.apache.avro"
    scope = "compile"
